### ISSUE TITLE
Walking paths with symlinks when FollowSymbolicLinks is set, can fail unexpectedly

### ISSUE THREAD

**Issue by chadnetzer** [karrick/godirwalk#13]
Construct the following dirs and links:

```
mkdir a b
touch z
ln -s ../b a/x
ln -s ../z b/y
```

Walking over the directories (starting at 'a') will result in the following error.:

cannot Stat: stat a/z: no such file or directory

The walked pathname `a/x/y`, which really just points to file `z`, should work perfectly fine, but the walk() func misconstructs the pathname when attempting to use Readlink() to build it's own direct path to `z` in order to Stat() it.

This occurs due to the following sequence of Joins for the Dir() and Readlink() referent:

```
Join(Dir("a/x"), "../b") => Join("a/", "../b") => "b"
Join(Dir("a/x/y"), "../z") => Join("a/x/", "../z") => "a/z"  # non-existant
```

The code is attempting to construct a new path, called 'osp' rather than just using the osPathname (or osChildname).  Rather than constructing a new path, the code could just os.Stat() on the original path containing the symlinks, since Stat() resolves those paths to reach the resulting file or directory.  Doing it this way (deleting all the code to build the 'osp' path), results in the normal tests all passing, and the walk over the constructed dirs/links described above to succeed (on Unix).

It seems the code originally worked this way, but it was changed in commit 3464826, which attributes the change to allowing proper walking of symlinks on Windows.  But the change seems to cause a regression for Unix.

Go's filepath package has the EvalSymlinks() func which appears to rewrite paths containing symlinks to a direct path without symlinks, presumably for situations like this.  The EvalSymlinks() code (which is a thin wrapper around walkSymlinks()), is reasonably complex, and itself calls Lstat() on each component of the path to determine which are symlinks.

Presuming there is no simple change to the 'osp' path construction that fixes this problem, the easiest "fix" for Unix appears to be to revert to the original code which simply calls Stat() on the original path to determine if the endpoint is a directory.  Using EvalSymlinks() for Windows might be the alternative way to fix it there (I'm unfamiliar with what the original problem was that this change was fixing).  There is some code duplication in the walk() function which could be factored out into a helper function, and then the helper function could be implemented appropriately for Unix and Windows.

Although the EvalSymlinks() func potentially does a lot of extra Lstats, it would only be used when FollowSymbolicLinks is set, and then only on the paths (and subpaths) that end in a symlink, so it may not have a huge impact overall (and it would only be on Windows, w/ the helper function approach).

I should be able to provide a WIP PR shortly which provides the failing testcase above, along with a version of the possible solution mentioned.

**Comment by adracus** [comment]
I'm facing this issue as well - any updates on this? The PR seems to be stale since last October. If desired, I'd update it / create a new one that finally fixes this issue.
