### ISSUE TITLE
go get fails: checksum mismatch

### ISSUE THREAD

**Issue by coolaj86** [karrick/godirwalk#19]
On Windows 10 with Go 1.11 I ran `go get github.com/UnnoTed/fileb0x`, which has this as a dependency, and I get this error:

```
go: verifying github.com/karrick/godirwalk@v1.7.3: checksum mismatch
        downloaded: h1:e5iv87oxunQtG7S9MB10jrINLmF7HecFSjiTYKO7P2c=
        go.sum:     h1:UP4CfXf1LfNwXrX6vqWf1DOhuiFRn2hXsqtRAQlQOUQ=
```

This also happens on CircleCI, but it doesn't happen on OS X.

I'm wondering if there isn't some CRLF or filename case sensitivity issues. Any thoughts?

**Comment by markbates** [comment]
This also fails with 1.7.5

**Comment by karrick** [comment]
I suppose this happened because on 2018-12-06 I did some changes to the test code, and modified the repository, yet did not tag the work because it was only test changes rather than library code changes.

I went ahead and tagged the new HEAD as v1.7.8.

**Comment by coolaj86** [comment]
The culprit is that go1.11.3 and go1.11.4 handle symlinks slightly differently and it affects package checksums.

See golang/go#29278

**Comment by karrick** [comment]
It bugs me a tiny bit, that I wrote a lot of the `go dep` code that did this checksumming, and that project was abandoned...

One of the reasons I wrote `godirwalk` was because of the non-uniform handling of `filepath.Walk` while working on Windows vs. UNIX.

Anyway, thanks for the link to that issue.

**Comment by karrick** [comment]
I just double-checked, and there is no more test scaffolding in this library. Those were removed in v1.7.6. So a clean checkout of `godirwalk` should not have those symbolic links, and all test scaffolding are dynamically created on Windows and UNIX using `ioutil.TempDir(os.TempDir(), "godirwalk-")`, which should not be anywhere near where this library is downloaded, tested, and built.

**Comment by coolaj86** [comment]
👍

**Comment by karrick** [comment]
Did this fix it?
