### ISSUE TITLE
How to ignore specific subdirectories or files ？

### ISSUE THREAD

**Issue by gonboy** [karrick/godirwalk#20]
if i use belown code,
```golang
Callback: func(osPathname string, de *godirwalk.Dirent){
   ignore some file.
}
```
I don't think ,it's a good idea.

**Comment by dallbee** [comment]
This is achievable. 

Skipping files doesn't really make sense. Lstat has already been performed on them, so just return.
Skipping directories:

```.go
Callback: func(osPathname string, de *godirwalk.Dirent) error {
    return filepath.SkipDir
}
```

**Comment by karrick** [comment]
I am not sure I understand the concern raised by @gonboy, but I definitely agree with @dallbee, in that the normal way to skip a file is to just return `nil` when you do not care about that file for some reason, and the normal way to skip an entire directory is to return the special token `filepath.SkipDir` from the Walk callback.

In the pasts some have requested a handle for skipping various VCS type files, but those are all specific to the task at hand and orthogonal to walking the directory. Any such orthogonal logic can be linked into a particular program and invoked during the client's callback function to cause the desired behavior.
