### ISSUE TITLE
Width First instead of Depth First walking possible?

### ISSUE THREAD

**Issue by spidgorny** [karrick/godirwalk#21]
AFAIK, the code walks into each folder it finds first. In my use case it would make more sense to go over 1st lever subfolders first, then go deeper into 2nd level subfolders.
Is this possible?

**Comment by karrick** [comment]
I do not want to ignore this issue, but I am not sure it's within the scope of this project at this time.

**Comment by xuyang2** [comment]
It seemds the code process each directory’s contents **after** the directory itself. 

https://github.com/karrick/godirwalk/blob/v1.17.0/walk.go#L277

https://github.com/karrick/godirwalk/blob/v1.17.0/walk.go#L338
