### ISSUE TITLE
Failed to build on Windows

### ISSUE THREAD

**Issue by beta** [karrick/godirwalk#25]
When building the latest version (v1.8.1) on Windows, the following error occurred:

```
# github.com/karrick/godirwalk
..\Go\pkg\mod\github.com\karrick\godirwalk@v1.8.1\follow_windows.go:10:6: evalSymlinksHelper redeclared in this block
        previous declaration at ..\Go\pkg\mod\github.com\karrick\godirwalk@v1.8.1\follow_unix.go:4:51
```

IMHO `_unix` in filename is not supported, as per golang/go#20322. Should build tags be added for Unix platforms?

**Comment by karrick** [comment]
I am so sorry for that. I will get these fixed as soon as I can get to my Windows laptop.
