### ISSUE TITLE
Error wrapping in ErrorCallback function

### ISSUE THREAD

**Issue by velut** [karrick/godirwalk#33]
Hi,

In the docs ErrorCallback is described like this

> When non-nil, this user supplied function is invoked with the OS pathname of the file system object that caused the error along with the error that took place

and WalkFunc like this

>  If an ErrorCallback function is provided, then it is invoked with the OS pathname of the node that caused the error along along with the error.

This suggests that errors are passed as-is to ErrorCallback.

However, due to error wrapping in `walk.go` 

https://github.com/karrick/godirwalk/blob/7fd96db52ca7845f37a669ae9ecc83c3719e7ee4/walk.go#L240

https://github.com/karrick/godirwalk/blob/7fd96db52ca7845f37a669ae9ecc83c3719e7ee4/walk.go#L316

the type of the error passed to ErrorCallback functions is different from the original error type, making comparisons like `if err == MyErr` fail (see https://play.golang.org/p/HlMFGvRepw0 for an example).

Is the error wrapping behavior necessary?

Thank you for your time.

**Comment by karrick** [comment]
Yeah this is a bug and I think the error wrapping is not a good idea. Thank you for pointing out this problem.
