### ISSUE TITLE
Consider providing an iterator to enumerate file system entry names

### ISSUE THREAD

**Issue by karrick** [karrick/godirwalk#34]
Rather than only providing a function that returns a slice of children entries, or an error, provide an iterator interface that can be used to scan through the child entries in a directory one by one, without allocating large amounts of RAM for large directories.

Additionally, for some operating systems the file system node type is not known without calling an operating system call like `stat` or `lstat`, and the present implementation of `walk` could fail when performing that `lstat` call to obtain file system node information merely when iterating through the contents of the children in the directory.  Once an iterator is available, update the `walk` implementation to enumerate through the children by using the iterator, which will allow the client software to receive an error for calling `lstat` for a given file, but allow the iteration of the directory contents to proceed.

**Comment by karrick** [comment]
Initial work being done on the scanner branch.

https://github.com/karrick/godirwalk/tree/scanner

**Comment by emosbaugh** [comment]
+1
