### ISSUE TITLE
Build error - s.sde.Reclen undefined

### ISSUE THREAD

**Issue by tuxillo** [karrick/godirwalk#41]
There is no d_reclen field in `struct dirent` in POSIX and some OSes (like DragonFly BSD) might not implement it.

```
# github.com/karrick/godirwalk
./scandir_unix.go:146:37: s.sde.Reclen undefined (type *syscall.Dirent has no field or method Reclen)

```

I'm wondering whether godirwalk could use the `ReadDirent/ParseDirent` combination instead of accessing Reclen directly. Since one of the key points of godirwalk, maybe `ParseDirent` is just slower and thus not used?

**Comment by karrick** [comment]
Thanks for opening this ticket to let me know it's not working for DragonFly BSD.

One of the reasons this library exists is to improve upon some of the perhaps negligible inefficiencies observed in the standard library implementation of reading a file system directory and walking a file system hierarchy. Performing some benchmarks on the results shows why some of those negligible inefficiencies are not quite negligible.

I think the proper course of action is to upgrade this library to work properly on DragonFly BSD.

**Comment by tuxillo** [comment]
Let me know how I can help :-)

**Comment by karrick** [comment]
I have not run DragonFly BSD for years. If you'd like to test the fix, I added it to the newly created `dragonfly` branch.

If you could check it out, and paste results of `git test -v` here, I would appreciate it.

**Comment by tuxillo** [comment]
Sure:

```
$ git branch
* dragonfly
  master
$ go test -v
# github.com/karrick/godirwalk [github.com/karrick/godirwalk.test]
./withoutReclen.go:8:15: undefined: namlen
FAIL    github.com/karrick/godirwalk [build failed]

```

**Comment by karrick** [comment]
@tuxillo , Oops, that was embarrassing. I forgot to double check it compiles for that GOOS. This commit fixes that typo.

I appreciate your efforts helping in this issue.

```
go test -v && for i in darwin dragonfly freebsd netbsd openbsd linux solaris ; do env GOOS=$i go build ; done
=== RUN   TestReadDirents
--- PASS: TestReadDirents (0.00s)
=== RUN   TestReadDirentsSymlinks
--- PASS: TestReadDirentsSymlinks (0.00s)
=== RUN   TestReadDirnames
--- PASS: TestReadDirnames (0.00s)
=== RUN   TestScanDir
=== RUN   TestScanDir/dirents
=== RUN   TestScanDir/dirnames
--- PASS: TestScanDir (0.00s)
    --- PASS: TestScanDir/dirents (0.00s)
    --- PASS: TestScanDir/dirnames (0.00s)
=== RUN   TestWalkCompatibleWithFilepathWalk
=== RUN   TestWalkCompatibleWithFilepathWalk/test_root
=== RUN   TestWalkCompatibleWithFilepathWalk/ignore_skips
--- PASS: TestWalkCompatibleWithFilepathWalk (0.00s)
    --- PASS: TestWalkCompatibleWithFilepathWalk/test_root (0.00s)
    --- PASS: TestWalkCompatibleWithFilepathWalk/ignore_skips (0.00s)
=== RUN   TestWalkSkipDir
=== RUN   TestWalkSkipDir/skip_file_at_root
=== RUN   TestWalkSkipDir/skip_dir_at_root
=== RUN   TestWalkSkipDir/skip_nodes_under_root
=== RUN   TestWalkSkipDir/SkipDirOnSymlink
--- PASS: TestWalkSkipDir (0.00s)
    --- PASS: TestWalkSkipDir/skip_file_at_root (0.00s)
    --- PASS: TestWalkSkipDir/skip_dir_at_root (0.00s)
    --- PASS: TestWalkSkipDir/skip_nodes_under_root (0.00s)
    --- PASS: TestWalkSkipDir/SkipDirOnSymlink (0.00s)
=== RUN   TestWalkFollowSymbolicLinks
--- PASS: TestWalkFollowSymbolicLinks (0.00s)
=== RUN   TestErrorCallback
=== RUN   TestErrorCallback/halt
=== RUN   TestErrorCallback/skipnode
--- PASS: TestErrorCallback (0.00s)
    --- PASS: TestErrorCallback/halt (0.00s)
    --- PASS: TestErrorCallback/skipnode (0.00s)
=== RUN   TestPostChildrenCallback
--- PASS: TestPostChildrenCallback (0.00s)
PASS
ok  	github.com/karrick/godirwalk	0.240s
```

**Comment by tuxillo** [comment]
Thanks! I've run the tests again in DragonFly, just in case:

```
$ go test -v
=== RUN   TestReadDirents
--- PASS: TestReadDirents (0.00s)
=== RUN   TestReadDirentsSymlinks
--- PASS: TestReadDirentsSymlinks (0.00s)
=== RUN   TestReadDirnames
--- PASS: TestReadDirnames (0.00s)
=== RUN   TestScanDir
=== RUN   TestScanDir/dirents
=== RUN   TestScanDir/dirnames
--- PASS: TestScanDir (0.00s)
    --- PASS: TestScanDir/dirents (0.00s)
    --- PASS: TestScanDir/dirnames (0.00s)
=== RUN   TestWalkCompatibleWithFilepathWalk
=== RUN   TestWalkCompatibleWithFilepathWalk/test_root
=== RUN   TestWalkCompatibleWithFilepathWalk/ignore_skips
--- PASS: TestWalkCompatibleWithFilepathWalk (0.00s)
    --- PASS: TestWalkCompatibleWithFilepathWalk/test_root (0.00s)
    --- PASS: TestWalkCompatibleWithFilepathWalk/ignore_skips (0.00s)
=== RUN   TestWalkSkipDir
=== RUN   TestWalkSkipDir/skip_file_at_root
=== RUN   TestWalkSkipDir/skip_dir_at_root
=== RUN   TestWalkSkipDir/skip_nodes_under_root
=== RUN   TestWalkSkipDir/SkipDirOnSymlink
--- PASS: TestWalkSkipDir (0.00s)
    --- PASS: TestWalkSkipDir/skip_file_at_root (0.00s)
    --- PASS: TestWalkSkipDir/skip_dir_at_root (0.00s)
    --- PASS: TestWalkSkipDir/skip_nodes_under_root (0.00s)
    --- PASS: TestWalkSkipDir/SkipDirOnSymlink (0.00s)
=== RUN   TestWalkFollowSymbolicLinks
--- PASS: TestWalkFollowSymbolicLinks (0.00s)
=== RUN   TestErrorCallback
=== RUN   TestErrorCallback/halt
=== RUN   TestErrorCallback/skipnode
--- PASS: TestErrorCallback (0.00s)
    --- PASS: TestErrorCallback/halt (0.00s)
    --- PASS: TestErrorCallback/skipnode (0.00s)
=== RUN   TestPostChildrenCallback
--- PASS: TestPostChildrenCallback (0.00s)
PASS
ok      github.com/karrick/godirwalk    0.061s

```

**Comment by karrick** [comment]
Do you want to try out any of the examples in the examples directory to make sure it works. I recommend https://github.com/karrick/godirwalk/blob/master/examples/find-fast/main.go

If you tell me all runs well, I will merge the branch back with master.

**Comment by karrick** [comment]
Actually, thinking again, provided the included test suite passed, that is all that I need to confirm it is able to both read directories, and to walk a hierarchy. If after I merge you ever notice a bug, please don't hesitate to open another issue.

Thank you for letting me know that DragonFly BSD support was broken.

**Comment by tuxillo** [comment]
I've tried them all but the `remove-empty-directories` one. See the results here:

https://leaf.dragonflybsd.org/~tuxillo/archive/temp/godirwalk/

BTW, we found this problem while trying to build `www/gitlab-pages` from our port repository, see:

https://sting.dragonflybsd.org/dports/logs/www___gitlab-pages.log

That gitlab-pages version has an older godirwalk version, hopefully I'll be able to apply your fix there.

Many thanks for your quick response :-)

**Comment by karrick** [comment]
I am very happy to help and have this working. I'm a huge BSD fan, but remember following Dragonfly back when it was first announced many years ago.

It seems you do a lot of bug reporting and PRs to support DragonFly. How did you get involved?

**Comment by tuxillo** [comment]
When I was young and naive I thought I could write some parts of an OS, etc :-D
Now I'm just focusing on what I like and trying to make things work better, which I think is a good compromise.

**Comment by karrick** [comment]
Yeah, I think most of us feel that way at some point. Green field, the perfect operating system, etc. Me too. I still have all my old notes. At this point, I realize how much work it would be, and realize that the limited time I have to share in the OSS world would likely never allow that much of a commitment. Don't hesitate to reach out if you need other Go + DragonFly BSD help, even with a different project. I cannot guarantee I will be able to jump on it right away, I would not mind lending a hand.

**Comment by karrick** [comment]
https://gitlab.com/gitlab-org/gitlab-pages/issues/316

**Comment by tuxillo** [comment]
Really appreciate your help. If you ever try DragonFly BSD again or if you just want a chat, please visit us in #dragonflybsd on EFNet.

**Comment by karrick** [comment]
https://gitlab.com/gitlab-org/gitlab-pages/merge_requests/215?commit_id=6df90126ae89940648b4c9420084e3fb789b46b5
