### ISSUE TITLE
Dirent.IsDir() returns false for symlinks to directories

### ISSUE THREAD

**Issue by sentriz** [karrick/godirwalk#44]
hi thank you for this project

i'm wondering how I can tell if a symlink to a directory is a directory, where in my case 
```
dirent.IsDir() = false
dirent.IsSymlink() = true
```

i think i saw a `isSymlinkToDirectory`, but it wasn't public

thanks!

`Linux manjaro 5.4.13-3-MANJARO #1 SMP PREEMPT Mon Jan 20 18:17:25 UTC 2020 x86_64 GNU/Linux`

**Comment by karrick** [comment]
Thanks for bringing up the issue. I think it might be a fair addition to the library to expose that directory.

**Comment by sentriz** [comment]
great to hear thank you :)
