### ISSUE TITLE
inquiry on the skipNode functionality in regards to file name filtering.

### ISSUE THREAD

**Issue by zkynet** [karrick/godirwalk#53]
Hello, I have been looking for a good package to walk directories for a while and I stumbled upon this one today. I really love the effort you have made into solving the issue with the path/filepath package provided by the go-team. 

However, I have one small issue. I was trying to implement a file name filter and it kind of felt a bit awkward. Here is an example: 

```golang
func main() {
	_ = godirwalk.Walk(".", &godirwalk.Options{
		Callback: func(osPathname string, de *godirwalk.Dirent) error {
			if strings.Contains(osPathname, ".git") {
				return errors.New("skipping: " + osPathname)
			}
			return nil
		},
	})
}
```

In the code sample above, I have implemented a word filter for the file path but if I keep the implementation like this, it will stop on the first math and not continue walking the directory. 

However if I add an error callback like so:

```golang
func main() {
	_ = godirwalk.Walk("./../..", &godirwalk.Options{
		Callback: func(osPathname string, de *godirwalk.Dirent) error {
			if strings.Contains(osPathname, ".git") {
				return errors.New("skipping: " + osPathname)
			}
			return nil
		},
		ErrorCallback: func(osPathname string, err error) godirwalk.ErrorAction {
			return godirwalk.SkipNode
		},
	})
}
```
We get the proper functionality where the walk only ignores the directory I returned an error for. 

This feels a bit awkward because now I am ignoring all errors in the error callback and I don´t want to do that by default. If I want to know which errors are filter(word match) errors I need to do another string check in the error callback function. 

```golang
func main() {
	_ = godirwalk.Walk("./../..", &godirwalk.Options{
		Callback: func(osPathname string, de *godirwalk.Dirent) error {
			if strings.Contains(osPathname, ".git") {
				return errors.New("path filter")
			}
			return nil
		},
		ErrorCallback: func(osPathname string, err error) godirwalk.ErrorAction {
			if err.Error() == "path filter" {
				return godirwalk.SkipNode
			}
			return godirwalk.Halt
		},
	})
}
```

Is there possibly a way to implement a file name/path filter in a better way that I am not seeing ? and if not, can I then perhaps take a shot at it and make a PR ? 

Regards,

**Comment by karrick** [comment]
You raise an incredibly valid issue, namely being able to skip a node and its descendants as soon as you come across it in the original callback.

I have updated the `find-fast` example program to demonstrate how to tell the Walk function how to skip a file system entry, and to not descend into its children.

Please re-open this issue if I misunderstood your request, but I think I have addressed your concerns.

**Comment by zkynet** [comment]
Hello again, 

I took a look at the find-fast example and it is indeed what I was looking for. However I was apparently not to detailed when creating the issue. 

I had already tried using the filepath.SkipDir but it seems to break the walk if I return that error on a file instead of a directory. 

I did some debugging on the walk function and you can view the video here:
https://www.twitch.tv/videos/708174351

I find the (possible) issue @ 56:30 in the video and then I implement a solution that works for me. 

However, I obviously don´t know all the logic behind this package and my solution might break something somewhere else so I would love it if you could check it out. 

Regards,
