### ISSUE TITLE
Thanks:  inquiry on the skipNode functionality in regards to file name filtering

### ISSUE THREAD

**Issue by zkynet** [karrick/godirwalk#56]
Sorry for the late reply, I´m timing my replies with the classes I have. 

The flag you created does exactly what we hoped it would. 

And yes, I was a bit surprised about the loop being broken on a file, but then again you are right about the documentation stating that it should. 

Thank for you updating this so quickly <3

**Comment by karrick** [comment]
I hope you find the improved API more user friendly. Good luck in your classes!
